[package]
name = "scraper"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.25", features = ["rustls-tls"] }
tokio = { version = "1.48.0", features = ["full"] }
scraper = "0.25"
